#!/bin/sh

### BEGIN INIT INFO
# Provides:          uwsgi
# Required-Start:    $all $syslog
# Required-Stop:     $all $syslog
# Default-Start:     3 4 5
# Default-Stop:      0 1 2 6
# Short-Description: starts the uwsgi app server
# Description:       starts uwsgi app server using start-stop-daemon
### END INIT INFO

PATH=/opt/uwsgi:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/local/bin/uwsgi

OWNER=root

NAME=wsgi_syndelesis
DESC=uwsgi

test -x $DAEMON || exit 0

# Include uwsgi defaults if available
if [ -f /etc/default/uwsgi ] ; then
        . /etc/default/uwsgi
fi

set -e

DAEMON_OPTS="--master --emperor /var/www/html/syndelesis/uwsgi.ini --die-on-term --uid root --gid root --logto /var/www/html/syndelesis/log/emperor.log"
 
case "$1" in
  start)
    echo -n "Starting $DESC: "
    start-stop-daemon --start --chuid $OWNER:$OWNER --user $OWNER --exec $DAEMON -- $DAEMON_OPTS &
    echo "$NAME."
    ;;
  stop)
    echo -n "Stopping $DESC: "
    start-stop-daemon --signal 3 --user $OWNER --quiet --retry 2 --stop --exec $DAEMON
    echo "$NAME."
    ;;
  restart)
    echo -n "Restarting $DESC: "
    start-stop-daemon --signal 3 --user $OWNER --quiet --retry 2 --stop --exec $DAEMON
    sleep 1
    start-stop-daemon --user $OWNER --start --quiet --chuid $OWNER:$OWNER --exec $DAEMON -- $DAEMON_OPTS &
    echo "$NAME."
    ;;
  *)  
    N=/etc/init.d/$NAME
    echo "Usage: $N {start|stop|restart}" >&2
    exit 1
    ;;
esac
exit 0
