"""empty message

Revision ID: f068c910c7a1
Revises: bb94425143cc
Create Date: 2017-12-10 16:06:14.005199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f068c910c7a1'
down_revision = 'bb94425143cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services_topics_map',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('input', sa.Boolean(), server_default='f', nullable=False),
    sa.Column('output', sa.Boolean(), server_default='f', nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('service_id', 'topic_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('services_topics_map')
    # ### end Alembic commands ###
