// host = '172.16.153.122';	// hostname or IP address
host = 'localhost';	// hostname or IP address
// host = '172.16.153.110';	// hostname or IP address
port = 3000;
topic = 'testnew';		// topic to subscribe to
useTLS = false;
//username = null;
//password = null;
username = "new";
password = "newnew2";
cleansession = true;
