# Dockerfile flask web app (application server)

# When we have the image...
#FROM vpitsilis/syntelesis-flask-app

# else run this from within syntelesis root dir to recreate docker image
FROM synaisthisi/syntelesis-flask-app:common

# run uWSGI with the ini file 
CMD ["uwsgi", "--ini", "uwsgi.ini"]
